"use client";

import {
  useState,
  useRef,
  useEffect,
  useCallback,
  useLayoutEffect,
} from "react";
import { motion, AnimatePresence } from "motion/react";
import {
  X,
  Play,
  Square,
  Circle,
  Download,
  Trash2,
  Zap,
  Loader2,
  RefreshCw,
  Mic,
} from "lucide-react";
import { useTracksStore } from "@/store/tracks";
import { getAudioContext } from "@/lib/audio-utils";
import { playDrum, DrumType, renderPatternToBuffer } from "@/lib/drum-synth";
import { v4 as uuidv4 } from "uuid";

// ─── constants ────────────────────────────────────────────────────────────────

const DRUMS = [
  { type: "kick"      as DrumType, name: "KICK",  key: "Q", color: "#FF3B30" },
  { type: "snare"     as DrumType, name: "SNARE", key: "W", color: "#FF9F0A" },
  { type: "closedhat" as DrumType, name: "C-HAT", key: "E", color: "#FFD60A" },
  { type: "openhat"   as DrumType, name: "O-HAT", key: "R", color: "#30D158" },
  { type: "clap"      as DrumType, name: "CLAP",  key: "A", color: "#00D4FF" },
  { type: "lowTom"    as DrumType, name: "TOM L", key: "S", color: "#5E5CE6" },
  { type: "midTom"    as DrumType, name: "TOM M", key: "D", color: "#BF5AF2" },
  { type: "rim"       as DrumType, name: "RIM",   key: "F", color: "#FF375F" },
];

const STEPS = 16;

function emptyPattern(): boolean[][] {
  return DRUMS.map(() => Array<boolean>(STEPS).fill(false));
}

// Fallback when no analysis available
function defaultPattern(): boolean[][] {
  const p = emptyPattern();
  [0, 4, 8, 12].forEach((s) => { p[0][s] = true; });
  [4, 12].forEach((s) => { p[1][s] = true; });
  [0, 2, 4, 6, 8, 10, 12, 14].forEach((s) => { p[2][s] = true; });
  p[4][4] = true; p[4][12] = true;
  return p;
}

// ─── waveform canvas ─────────────────────────────────────────────────────────

function HumWaveform({ audioBuffer }: { audioBuffer: AudioBuffer | null }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useLayoutEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas || !audioBuffer) return;

    const dpr = window.devicePixelRatio ?? 1;
    canvas.width = canvas.offsetWidth * dpr;
    canvas.height = canvas.offsetHeight * dpr;

    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const data = audioBuffer.getChannelData(0);
    const w = canvas.width;
    const h = canvas.height;
    const samplesPerPx = Math.floor(data.length / w);
    const cy = h / 2;

    ctx.clearRect(0, 0, w, h);

    // Gradient fill: purple → cyan
    const grad = ctx.createLinearGradient(0, 0, w, 0);
    grad.addColorStop(0, "#A855F799");
    grad.addColorStop(1, "#00D4FF99");
    ctx.fillStyle = grad;

    for (let x = 0; x < w; x++) {
      let min = 0, max = 0;
      for (let i = 0; i < samplesPerPx; i++) {
        const v = data[x * samplesPerPx + i] ?? 0;
        if (v < min) min = v;
        if (v > max) max = v;
      }
      const yTop = cy - max * cy * 0.88;
      const yBot = cy - min * cy * 0.88;
      ctx.fillRect(x / dpr, yTop / dpr, 1 / dpr, Math.max(1 / dpr, (yBot - yTop) / dpr));
    }
  }, [audioBuffer]);

  if (!audioBuffer) return null;

  return (
    <canvas
      ref={canvasRef}
      className="flex-1 h-full"
      style={{ imageRendering: "pixelated" }}
    />
  );
}

// ─── component ────────────────────────────────────────────────────────────────

interface BeatMakerProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function BeatMaker({ isOpen, onClose }: BeatMakerProps) {
  const { analysis, tracks, addTrack } = useTracksStore();
  const humTrack = tracks.find((t) => t.type === "hum");

  const [pattern, setPattern] = useState<boolean[][]>(defaultPattern);
  const [bpm, setBpm] = useState(120);
  const [isPlaying, setIsPlaying] = useState(false);
  const [isRecording, setIsRecording] = useState(false);
  const [currentStep, setCurrentStep] = useState(-1);
  const [padActive, setPadActive] = useState<boolean[]>(DRUMS.map(() => false));
  const [isExporting, setIsExporting] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  // Sync BPM from analysis whenever it changes
  useEffect(() => {
    if (analysis?.tempo) setBpm(analysis.tempo);
  }, [analysis?.tempo]);

  // Scheduler refs
  const schedulerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const nextNoteTimeRef = useRef(0);
  const stepRef = useRef(0);
  const bpmRef = useRef(bpm);
  const patternRef = useRef(pattern);
  const isPlayingRef = useRef(false);
  const isRecordingRef = useRef(isRecording);
  const hasAutoGeneratedRef = useRef(false);

  useEffect(() => { bpmRef.current = bpm; }, [bpm]);
  useEffect(() => { patternRef.current = pattern; }, [pattern]);
  useEffect(() => { isRecordingRef.current = isRecording; }, [isRecording]);

  // Reset auto-generate flag when analysis changes (new hum)
  useEffect(() => {
    hasAutoGeneratedRef.current = false;
  }, [analysis]);

  // ─── generate beat from hum ────────────────────────────────────────────────

  const generateFromHum = useCallback(async () => {
    if (!analysis) return;
    setIsGenerating(true);
    try {
      const res = await fetch("/api/generate-beat-pattern", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          key: analysis.key,
          tempo: analysis.tempo,
          mood: analysis.mood,
          genre: analysis.genre,
          melody: analysis.melody, // rhythm-informed beat generation
        }),
      });
      if (!res.ok) throw new Error("API error");
      const { pattern: newPattern } = await res.json();
      setPattern(newPattern);
    } catch (err) {
      console.error("Beat pattern generation failed:", err);
      // keep current pattern on failure
    }
    setIsGenerating(false);
  }, [analysis]);

  // Auto-generate when opened with analysis for the first time
  useEffect(() => {
    if (isOpen && analysis && !hasAutoGeneratedRef.current) {
      hasAutoGeneratedRef.current = true;
      generateFromHum();
    }
  }, [isOpen, analysis, generateFromHum]);

  // ─── scheduler ──────────────────────────────────────────────────────────────

  const runScheduler = useCallback(() => {
    const ctx = getAudioContext();
    const spStep = 60 / bpmRef.current / 4;

    while (nextNoteTimeRef.current < ctx.currentTime + 0.12) {
      const step = stepRef.current;
      const time = nextNoteTimeRef.current;

      patternRef.current.forEach((row, di) => {
        if (row[step]) playDrum(DRUMS[di].type, time);
      });

      const delay = Math.max(0, (time - ctx.currentTime) * 1000);
      setTimeout(() => setCurrentStep(step), delay);

      nextNoteTimeRef.current += spStep;
      stepRef.current = (stepRef.current + 1) % STEPS;
    }
    schedulerRef.current = setTimeout(runScheduler, 25);
  }, []);

  const startPlayback = useCallback(() => {
    const ctx = getAudioContext();
    stepRef.current = 0;
    nextNoteTimeRef.current = ctx.currentTime + 0.05;
    isPlayingRef.current = true;
    setIsPlaying(true);
    runScheduler();
  }, [runScheduler]);

  const stopPlayback = useCallback(() => {
    isPlayingRef.current = false;
    if (schedulerRef.current) clearTimeout(schedulerRef.current);
    setIsPlaying(false);
    setCurrentStep(-1);
    stepRef.current = 0;
  }, []);

  useEffect(() => {
    if (!isOpen) stopPlayback();
    return () => stopPlayback();
  }, [isOpen, stopPlayback]);

  // ─── keyboard shortcuts ────────────────────────────────────────────────────

  const hitPad = useCallback((drumIdx: number) => {
    playDrum(DRUMS[drumIdx].type);
    setPadActive((prev) => prev.map((a, i) => (i === drumIdx ? true : a)));
    setTimeout(
      () => setPadActive((prev) => prev.map((a, i) => (i === drumIdx ? false : a))),
      130
    );
    if (isRecordingRef.current && isPlayingRef.current) {
      const step = stepRef.current;
      setPattern((prev) =>
        prev.map((row, i) =>
          i === drumIdx ? row.map((v, s) => (s === step ? true : v)) : row
        )
      );
    }
  }, []);

  useEffect(() => {
    if (!isOpen) return;
    const keyMap: Record<string, number> = {};
    DRUMS.forEach((d, i) => { keyMap[d.key.toLowerCase()] = i; });
    const onKeyDown = (e: KeyboardEvent) => {
      if ((e.target as HTMLElement).tagName === "INPUT") return;
      if (e.repeat) return;
      const idx = keyMap[e.key.toLowerCase()];
      if (idx !== undefined) hitPad(idx);
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [isOpen, hitPad]);

  // ─── export ─────────────────────────────────────────────────────────────────

  const exportToTrack = async () => {
    setIsExporting(true);
    try {
      const buffer = await renderPatternToBuffer(
        patternRef.current,
        DRUMS.map((d) => d.type),
        bpmRef.current,
        4
      );
      const label = analysis
        ? `${analysis.genre} beat · ${bpmRef.current} BPM`
        : `Beat ${bpmRef.current} BPM`;
      addTrack({
        id: uuidv4(),
        name: label,
        type: "beat",
        audioUrl: null,
        audioBuffer: buffer,
        volume: 0.8,
        muted: false,
        solo: false,
        color: "#FF3B30",
        isLoading: false,
      });
      stopPlayback();
      onClose();
    } catch (err) {
      console.error("Beat export failed:", err);
    }
    setIsExporting(false);
  };

  // ─── render ─────────────────────────────────────────────────────────────────

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.15 }}
          className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4"
          onPointerDown={(e) => {
            if (e.target === e.currentTarget) { stopPlayback(); onClose(); }
          }}
        >
          <motion.div
            initial={{ scale: 0.96, y: 24, opacity: 0 }}
            animate={{ scale: 1, y: 0, opacity: 1 }}
            exit={{ scale: 0.96, y: 24, opacity: 0 }}
            transition={{ type: "spring", stiffness: 320, damping: 28 }}
            className="daw-panel w-full max-w-5xl rounded-xl overflow-hidden relative noise-overlay"
            onPointerDown={(e) => e.stopPropagation()}
          >
            {/* rack screws */}
            <div className="absolute top-3 left-3 rack-screw" />
            <div className="absolute top-3 right-3 rack-screw" />

            {/* ── Header row 1: controls ── */}
            <div className="flex items-center gap-3 px-5 py-3 border-b border-[#2A2A2E] bg-[#111114] flex-wrap">
              <div className="flex items-center gap-2">
                <Zap
                  className="w-3.5 h-3.5 text-[#FF3B30]"
                  style={{ filter: "drop-shadow(0 0 5px #FF3B3080)" }}
                />
                <span className="text-[11px] uppercase tracking-[0.15em] text-[#E0E0E4] font-semibold font-[family-name:var(--font-display)]">
                  Beat Maker
                </span>
              </div>

              {/* BPM */}
              <div className="lcd-display flex items-center gap-2 px-3 py-1.5">
                <span className="text-[9px] text-[#505058] uppercase tracking-wider">BPM</span>
                <input
                  type="number"
                  min={60}
                  max={240}
                  value={bpm}
                  onChange={(e) =>
                    setBpm(Math.max(60, Math.min(240, Number(e.target.value))))
                  }
                  className="w-10 bg-transparent text-[12px] led-green font-mono tabular-nums outline-none text-center"
                />
              </div>
              <input
                type="range"
                min={60}
                max={200}
                value={bpm}
                onChange={(e) => setBpm(Number(e.target.value))}
                className="w-28 accent-[#00FF87] cursor-pointer"
              />

              {/* Transport */}
              <div className="flex items-center gap-2">
                <motion.button
                  whileTap={{ scale: 0.9 }}
                  onClick={isPlaying ? stopPlayback : startPlayback}
                  className={`flex items-center gap-1.5 px-3 h-7 rounded text-[10px] font-semibold uppercase tracking-wider transition-all ${
                    isPlaying
                      ? "bg-[#FF3B30]/20 border border-[#FF3B30]/50 text-[#FF3B30]"
                      : "bg-[#232328] border border-[#2A2A2E] text-[#E0E0E4] hover:border-[#00FF87]/50 hover:text-[#00FF87]"
                  }`}
                >
                  {isPlaying ? <Square className="w-2.5 h-2.5" /> : <Play className="w-2.5 h-2.5" />}
                  {isPlaying ? "Stop" : "Play"}
                </motion.button>

                <motion.button
                  whileTap={{ scale: 0.9 }}
                  onClick={() => setIsRecording((r) => !r)}
                  title="Record live pad hits while playing"
                  className={`flex items-center gap-1.5 px-3 h-7 rounded text-[10px] font-semibold uppercase tracking-wider transition-all ${
                    isRecording
                      ? "bg-[#FF3B30] border border-[#FF3B30] text-white recording-pulse"
                      : "bg-[#232328] border border-[#2A2A2E] text-[#505058] hover:border-[#FF3B30]/40 hover:text-[#FF3B30]"
                  }`}
                >
                  <Circle className="w-2.5 h-2.5 fill-current" />
                  Rec
                </motion.button>
              </div>

              <div className="flex items-center gap-2 ml-auto">
                <motion.button
                  whileTap={{ scale: 0.9 }}
                  onClick={() => setPattern(emptyPattern())}
                  className="flex items-center gap-1.5 px-2.5 h-7 rounded text-[9px] uppercase tracking-wider bg-[#232328] border border-[#2A2A2E] text-[#505058] hover:text-[#E0E0E4] transition-all"
                >
                  <Trash2 className="w-3 h-3" /> Clear
                </motion.button>

                <motion.button
                  whileTap={{ scale: 0.9 }}
                  onClick={exportToTrack}
                  disabled={isExporting}
                  className="flex items-center gap-1.5 px-2.5 h-7 rounded text-[9px] uppercase tracking-wider bg-[#A855F7]/20 border border-[#A855F7]/40 text-[#A855F7] hover:bg-[#A855F7]/30 transition-all disabled:opacity-50"
                >
                  {isExporting ? <Loader2 className="w-3 h-3 animate-spin" /> : <Download className="w-3 h-3" />}
                  {isExporting ? "Rendering…" : "Export Track"}
                </motion.button>

                <motion.button
                  whileTap={{ scale: 0.9 }}
                  onClick={() => { stopPlayback(); onClose(); }}
                  className="w-7 h-7 rounded flex items-center justify-center bg-[#232328] border border-[#2A2A2E] text-[#505058] hover:text-[#E0E0E4] transition-all"
                >
                  <X className="w-3.5 h-3.5" />
                </motion.button>
              </div>
            </div>

            {/* ── Header row 2: hum context ── */}
            {analysis ? (
              <div className="flex items-center gap-3 px-5 border-b border-[#2A2A2E] bg-[#0D0D10] h-11">
                {/* Hum source label */}
                <div className="flex items-center gap-1.5 shrink-0">
                  <Mic className="w-3 h-3 text-[#A855F7]" />
                  <span className="text-[9px] text-[#505058] uppercase tracking-wider">
                    Hum Source
                  </span>
                </div>

                {/* Analysis badges */}
                <div className="flex items-center gap-1.5 shrink-0">
                  {[
                    { label: analysis.key, color: "#A855F7" },
                    { label: `${analysis.tempo} BPM`, color: "#00FF87" },
                    { label: analysis.mood, color: "#00D4FF" },
                    { label: analysis.genre, color: "#FF9F0A" },
                  ].map(({ label, color }) => (
                    <span
                      key={label}
                      className="text-[8px] px-1.5 py-0.5 rounded-sm border uppercase tracking-wider font-mono"
                      style={{
                        color,
                        borderColor: `${color}40`,
                        backgroundColor: `${color}12`,
                      }}
                    >
                      {label}
                    </span>
                  ))}
                </div>

                {/* Waveform */}
                <div className="flex-1 h-6 min-w-0">
                  <HumWaveform audioBuffer={humTrack?.audioBuffer ?? null} />
                </div>

                {/* Regen button */}
                <motion.button
                  whileTap={{ scale: 0.9 }}
                  onClick={generateFromHum}
                  disabled={isGenerating}
                  className="shrink-0 flex items-center gap-1.5 px-2.5 h-7 rounded text-[9px] uppercase tracking-wider bg-[#A855F7]/15 border border-[#A855F7]/30 text-[#A855F7] hover:bg-[#A855F7]/25 transition-all disabled:opacity-40"
                >
                  {isGenerating ? (
                    <Loader2 className="w-3 h-3 animate-spin" />
                  ) : (
                    <RefreshCw className="w-3 h-3" />
                  )}
                  Regen from hum
                </motion.button>
              </div>
            ) : (
              <div className="flex items-center gap-2 px-5 border-b border-[#2A2A2E] bg-[#0D0D10] h-9">
                <Mic className="w-3 h-3 text-[#3A3A42]" />
                <span className="text-[9px] text-[#3A3A42] tracking-wider">
                  Record a hum to generate a contextual beat pattern
                </span>
              </div>
            )}

            {/* ── Sequencer Grid ── */}
            <div className="px-5 pt-4 pb-3 relative">
              {/* Loading overlay */}
              <AnimatePresence>
                {isGenerating && (
                  <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    className="absolute inset-0 z-10 bg-[#0D0D0F]/85 backdrop-blur-[2px] flex items-center justify-center rounded"
                  >
                    <div className="flex flex-col items-center gap-3">
                      <div className="flex items-center gap-2">
                        <Loader2 className="w-4 h-4 animate-spin text-[#A855F7]" />
                        <span className="text-[11px] text-[#A855F7] uppercase tracking-wider">
                          Generating beat from your hum…
                        </span>
                      </div>
                      <div className="flex gap-1">
                        {DRUMS.map((d, i) => (
                          <motion.div
                            key={d.type}
                            className="w-1 rounded-full"
                            style={{ backgroundColor: d.color }}
                            animate={{ height: [4, 12, 4] }}
                            transition={{
                              duration: 0.6,
                              repeat: Infinity,
                              delay: i * 0.08,
                              ease: "easeInOut",
                            }}
                          />
                        ))}
                      </div>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Step number header */}
              <div className="flex mb-2" style={{ paddingLeft: 76 }}>
                {Array.from({ length: STEPS }, (_, i) => (
                  <div
                    key={i}
                    className={`flex-1 text-center text-[8px] font-mono transition-colors duration-75 ${
                      i % 4 === 0 && i > 0 ? "ml-[3px]" : ""
                    } ${
                      currentStep === i
                        ? "text-[#00FF87]"
                        : i % 4 === 0
                          ? "text-[#505058]"
                          : "text-[#2A2A2E]"
                    }`}
                  >
                    {i % 4 === 0 ? i / 4 + 1 : "·"}
                  </div>
                ))}
              </div>

              {/* Drum rows */}
              {DRUMS.map((drum, di) => (
                <div key={drum.type} className="flex items-center mb-[5px]">
                  <div className="shrink-0 flex items-center gap-2" style={{ width: 76 }}>
                    <div
                      className="w-1.5 h-1.5 rounded-full shrink-0"
                      style={{
                        backgroundColor: drum.color,
                        boxShadow: `0 0 5px ${drum.color}80`,
                      }}
                    />
                    <span className="text-[9px] text-[#606068] font-mono uppercase tracking-wider">
                      {drum.name}
                    </span>
                  </div>

                  {Array.from({ length: STEPS }, (_, step) => {
                    const on = pattern[di][step];
                    const active = currentStep === step;
                    const groupGap = step % 4 === 0 && step > 0;
                    return (
                      <div
                        key={step}
                        className={`flex-1 px-[2px] ${groupGap ? "pl-[4px]" : ""}`}
                      >
                        <button
                          onClick={() => toggleStep(di, step)}
                          className="w-full h-7 rounded-[3px] transition-all duration-75"
                          style={{
                            backgroundColor: on
                              ? active ? drum.color : `${drum.color}BB`
                              : active
                                ? "#252528"
                                : step % 8 < 4 ? "#18181B" : "#141417",
                            border: `1px solid ${
                              on ? `${drum.color}70` : active ? "#3A3A42" : "#222226"
                            }`,
                            boxShadow:
                              on && active
                                ? `0 0 12px ${drum.color}90, inset 0 0 8px ${drum.color}30`
                                : on
                                  ? `0 0 5px ${drum.color}40`
                                  : "none",
                            transform: on && active ? "scale(1.05)" : "scale(1)",
                          }}
                        />
                      </div>
                    );
                  })}
                </div>
              ))}
            </div>

            {/* ── Live Pads ── */}
            <div className="border-t border-[#1E1E22] px-5 pt-3 pb-5">
              <p className="text-[8px] text-[#3A3A42] uppercase tracking-[0.1em] mb-2.5">
                Live Pads · Q&nbsp;W&nbsp;E&nbsp;R / A&nbsp;S&nbsp;D&nbsp;F
              </p>
              <div className="grid grid-cols-8 gap-2">
                {DRUMS.map((drum, idx) => (
                  <motion.button
                    key={drum.type}
                    onPointerDown={(e) => { e.preventDefault(); hitPad(idx); }}
                    whileTap={{ scale: 0.9 }}
                    className="h-16 rounded-lg flex flex-col items-center justify-center gap-1 select-none cursor-pointer transition-all duration-75"
                    style={{
                      backgroundColor: padActive[idx] ? `${drum.color}28` : "#17171A",
                      border: `1px solid ${padActive[idx] ? drum.color : "#2A2A2E"}`,
                      boxShadow: padActive[idx]
                        ? `0 0 22px ${drum.color}50, inset 0 0 14px ${drum.color}18`
                        : "inset 0 1px 0 rgba(255,255,255,0.03)",
                    }}
                  >
                    <span
                      className="text-[11px] font-bold tracking-wide"
                      style={{
                        color: padActive[idx] ? drum.color : "#606068",
                        textShadow: padActive[idx] ? `0 0 8px ${drum.color}80` : "none",
                      }}
                    >
                      {drum.name}
                    </span>
                    <span
                      className="text-[9px] font-mono"
                      style={{ color: padActive[idx] ? `${drum.color}AA` : "#3A3A42" }}
                    >
                      [{drum.key}]
                    </span>
                  </motion.button>
                ))}
              </div>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );

  function toggleStep(drumIdx: number, step: number) {
    setPattern((prev) =>
      prev.map((row, i) =>
        i === drumIdx ? row.map((v, s) => (s === step ? !v : v)) : row
      )
    );
  }
}
